spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level: DEBUG
    root:  DEBUG
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR