spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8

  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/static/


server:
  port: 8080
  ssl:
    key-store:
logging:
  level:
    root:  DEBUG
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.linlinjava.litemall.core:  DEBUG
    org.linlinjava.litemall.db:  DEBUG
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  DEBUG
  path: D:/logs/